spring:
  datasource:
    url: jdbc:postgresql://localhost:15432/page2screen
    username: page2screen
    password: page2screen
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate.jdbc.time_zone: UTC
  thymeleaf:
    cache: false
server:
  port: 8080
